### ISSUE TITLE
Support for Postgres 14 (default config)

### ISSUE THREAD

**Issue by jokay** [pgmodeler/pgmodeler#1658]
**Feature description**

pgModeler **0.9.3** *(AppImage)* is not able to connect to Postgres 14 *(default config)*.

SCRAM authentication seems to be the **default** for postgres **>= 14.x**, see [here](https://www.percona.com/blog/postgresql-14-and-recent-scram-authentication-changes-should-i-migrate-to-scram/).

**Sample image**

![image](https://user-images.githubusercontent.com/18613935/154421538-9a156061-6d32-4ecc-92c3-0be360653b9b.png)

**Additional info**

We are using the official [Docker postgres](https://hub.docker.com/_/postgres) without any custom settings.

```yml
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=p@55w0rd
    networks:
      - default
    ports:
      - 5432:5432
```

Relates https://github.com/pgmodeler/pgmodeler/issues/1034.
